config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('', include('page.urls')),
    path('tenshu/admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls')),
    path('', include('register.urls')),
    path('password_reset/', views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

page/urls.py
from django.urls import path
from . import views
app_name = 'page'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('page/<pk>', views.ShopList.as_view(), name='shoplist'),
    # path('', views.IndexView.as_view(), name='index'),
    path('page/<slug:slug>/', views.ShopTop.as_view(), name='shoptop'),
    # path('page/<uuid>/admin/', views.IndexView.as_view(), name='index'),
    path('page/<pk>/admin/create/', views.ShopCreateView.as_view(), name='shopcreate'),
    path('page/<pk>/<slug>/update/', views.ShopUpdateView.as_view(), name='shopupdate'),
    # path('page/<uuid>/admin/delete', views.IndexView.as_view(), name='index'),
]

register/urls.py
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'register'

urlpatterns = [
    path('login/lock', views.LoginLockView.as_view(), name='loginlock'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('login/', views.LoginView.as_view(form_class=LoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('top/<pk>/', views.UserTop.as_view(), name='usertop'),
    path('password_change', views.PasswordChange.as_view(), name='password_change'),
    path('account/', views.account_redirect, name='account-redirect'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>', views.EmailChangeComplete.as_view(),name='email_change_complete'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

page/models.py
from django.db import models
from register.models import User

class Shop(models.Model):
    """ お店情報を持つmodel """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    eyecatch_image = models.ImageField(upload_to='images', blank=True, null=True)
    name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15)
    access = models.CharField(max_length=30)
    buisiness_time1 = models.CharField(max_length=30)
    buisiness_time2 = models.CharField(max_length=30)
    non_buisiness_day = models.CharField(max_length=30)
    seats = models.CharField(max_length=3)
    park = models.CharField(max_length=30)
    youtube_url = models.CharField(max_length=100)
    twitter_id = models.CharField(max_length=100)
    twitter_url = models.URLField(max_length=100)
    greeting = models.TextField(max_length=500)

    def __str__(self):
        return self.name
    
    

page/templates/page/index.html
{% extends "register/base.html" %}
{% block content %}
<div class="index">
    <h2 class="first-p">店主.jpとは</h2>
    <p>主に個人店のラーメン店主様向けのシンプルなホームページ作成サービスです。</p>
    <p>必要な情報を入力するだけですぐにお手軽にお店のページをお持ちいただけます。</p>

    <h2>店主.jpの特徴</h2>
    <h3>Twitter対応</h3>
    <p>Twitterで集客、告知している店主様のために対応致しました。</p>
    <p>お作りいただいた簡易ホームページにご自身のタイムラインを掲載していただくことができます。</p>

    <h3>Youtube対応</h3>
    <p>作成されたYoutube動画を掲載していただくことが出来ます。</p>
    <p>自己紹介、告知、宣伝、仕込み動画等にお役立てくださいませ。</p>
    <p class="last-p">近日サービス開始予定！</p>
</div>

{% endblock %}

page/templates/page/shop.html
{% load static %}


<!DOCTYPE html>
<html>
 
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'page/style.css' %}">
    <title>ListViewサンプル</title>
</head>
 
<body>
<h1>{{ object.name }}</h1>
<br>

    <iframe width="90%" height="315" src="{{ object.youtube_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br>

    <p>{{ object.greeting }}</p>
    <br>

    <a class="twitter-timeline" height="400px" width="90%" href="{{ object.twitter_url }}">
        </a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <br>

    <table border="1">
        <tr>
            <th>電話番号</th>
            <td>{{ object.phone_number }}</td>
        </tr>
        <tr>
            <th>アクセス</th>
            <td>{{ object.access }}</td>
        </tr>
        <tr>
            <th>営業時間</th>
            <td>{{ object.buisiness_time1 }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ object.buisiness_time2 }}</td>
        </tr>
        <tr>
            <th>定休日</th>
            <td>{{ object.non_buisiness_day }}</td>
        </tr>
        <tr>
            <th>席数</th>
            <td>{{ object.seats }}</td>
        </tr>
        <tr>
            <th>駐車場</th>
            <td>{{ object.park }}</td>
        </tr>
    </table>
    <br>

</body>
 
</html>

page/templates/page/shopcreate.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">作成</button>
</form>
<p class="last-p"><a href="{% url 'register:usertop' user.id %}">ユーザートップページへ戻る</a></p>
{% endblock %}

page/templates/page/shoplist.html
{% extends 'register/base.html' %}
{% block content %}
{% if request.user.pk == user.pk %}
{% if shop_list %}
{% for shop in shop_list %}
    <div class="hello">
        <p>{{ shop.name }}</p>
    </div>
    <p><a href="{% url 'page:shopupdate' shop.pk shop.slug %}">{{ shop.name }}更新ページへ</a></p>
    <p class="last-p"><a href="{% url 'page:shoptop' shop.slug %}">{{ shop.name }}ショップページへ</a></p>
{% endfor %}
    <p class="last-p"><a href="{% url 'register:usertop' user.id %}">ユーザートップページへ戻る</a></p>

{% else %}
    <p class="last-p">お店がありません</p>
{% endif %}
{% else %}
    <p class="last-p">お店がありません</p>
{% endif %}
{% comment %} {% endif %} {% endcomment %}
{% endblock %}

page/templates/page/shopupdate.html
{% extends 'register/base.html' %}

 
{% block content %}
    <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
    <p><a href="{% url 'register:shoplist' user.id %}">お店サイト管理ページへ</a></p>

{% endblock %}
 
</html>