config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('', include('page.urls')),
    path('tenshu/admin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls')),
    path('', include('register.urls')),
    path('password_reset/', views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

page/urls.py
from django.urls import path
from . import views
app_name = 'page'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('page/<pk>', views.ShopList.as_view(), name='shoplist'),
    # path('', views.IndexView.as_view(), name='index'),
    path('page/<slug:slug>/', views.ShopTop.as_view(), name='shoptop'),
    # path('page/<uuid>/admin/', views.IndexView.as_view(), name='index'),
    path('page/<pk>/admin/create/', views.ShopCreateView.as_view(), name='shopcreate'),
    path('page/<pk>/<slug>/update/', views.ShopUpdateView.as_view(), name='shopupdate'),
    # path('page/<uuid>/admin/delete', views.IndexView.as_view(), name='index'),
]

register/urls.py
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'register'

urlpatterns = [
    path('login/lock', views.LoginLockView.as_view(), name='loginlock'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('login/', views.LoginView.as_view(form_class=LoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('top/<pk>/', views.UserTop.as_view(), name='usertop'),
    path('password_change', views.PasswordChange.as_view(), name='password_change'),
    path('account/', views.account_redirect, name='account-redirect'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>', views.EmailChangeComplete.as_view(),name='email_change_complete'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

register/models.py
import uuid
from django.conf import settings
from django.db import models
from django.core.mail import BadHeaderError, send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.mail import EmailMessage
from django.http import HttpResponse


class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル

    usernameを使わず、emailアドレスをユーザー名として使うようにしています。

    """
    email = models.EmailField(_('email address'), unique=True, error_messages={'invalid_login':"5回連続でログインに失敗すると安全のためアカウントを一時的にロック致します。"
                                                                                "ご了承ください",
                                                                                })
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name
        
    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        print('ここまで来た')

        try:
            send_mail(subject, message, from_email, [self.email], fail_silently=False, **kwargs)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

    @property
    def username(self):
        return self.email

register/forms.py
from django.contrib.auth.forms import (
    UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm,
    AuthenticationForm,
)
from django.contrib.auth import get_user_model, authenticate
from django import forms
from django.utils.text import capfirst

User = get_user_model()

class LoginForm(AuthenticationForm):
    """ ログインフォーム """

    error_messages = {
        'invalid_login': ("5回連続でログインに失敗すると安全のためアカウントを一時的にロック致します。"
                           "ご了承ください"),
        'inactive': ("This account is inactive."),
    }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class UserCreateForm(UserCreationForm):
    """ ユーザー登録用フォーム """
    class Meta:
        model = User
        fields = ('email',)
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # 仮登録段階でアカウントを一度削除
    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class MyPasswordChangeForm(PasswordChangeForm):
    """ パスワード変更フォーム """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class EmailChangeForm(forms.ModelForm):
    """ メールアドレス変更フォーム """
    class Meta:
        model = User
        fields = ('email',)
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # 仮登録段階でアカウントを一度削除
    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

register/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, dumps, loads
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    DetailView, ListView, TemplateView, CreateView, FormView
)

from .forms import (
    LoginForm, UserCreateForm, MyPasswordChangeForm, EmailChangeForm,
    MyPasswordResetForm, MySetPasswordForm
)
from .models import User
from page.models import Shop

from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse

User = get_user_model()

class LoginLockView(TemplateView):
    """ ログイン5回連続で失敗したら表示 """
    template_name = 'register/axes_locked.html'

class UserCreate(CreateView):
    """ ユーザー仮登録 """
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """ 仮登録と本登録用メールの発行 """
        # is_active= Falseは仮登録か退会
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送信
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)
        from_email = settings.DEFAULT_FROM_EMAIL
        user.email_user(subject,
        message,
        from_email)
        return redirect('register:user_create_done')

class UserCreateDone(TemplateView):
    """ ユーザー仮登録完了 """
    template_name = 'register/user_create_done.html'

class UserCreateComplete(TemplateView):
    """ アクティベーションURLを開いたあとの処理 """
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATE_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        """ tokenが正しければ本登録 """
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # token 間違い
        except BadSignature:
            print('tokenが間違っています')
            return HttpResponseBadRequest()

        # token OK
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 本登録
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

            return HttpResponseBadRequest()


class Login(LoginView):
    """ ログイン """
    # form_class = LoginForm
    authentication_form = LoginForm
    
    template_name = 'registration/login.html'

@login_required
def account_redirect(request):
    """ ログインしたらメール送信してユーザートップページにつなぐ """
    subject = "ログインのお知らせ"

    message = "ログインのお知らせです。"

    from_email = settings.DEFAULT_FROM_EMAIL
    recipient_list = [

    from_email

    ]

    # send_mail(subject, message, from_email, recipient_list)
    return redirect('register:usertop', pk=request.user.pk)

class Logout(LoginRequiredMixin, LogoutView):
    """ ログアウト """
    template_name = 'register/logout.html'

class UserTop(LoginRequiredMixin, DetailView):
    """ ユーザートップページ """
    template_name = 'register/usertop.html'
    model = User

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['shop_list'] = Shop.objects.all()
        return context



class PasswordChange(PasswordChangeView):
    """ パスワード変更 """
    form_class = MyPasswordChangeForm
    template_name = 'register/password_change.html'
    success_url = reverse_lazy('register:account-redirect')

    def form_valid(self, form):
        """ メッセージ表示を追加 """
        result = super().form_valid(form)
        messages.success(
            self.request, '「パスワード」を変更しました')
        return result

class EmailChange(LoginRequiredMixin, FormView):
    """ メールアドレスの変更 """
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        """ パスワード変更のためのメール送信 """
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')

class EmailChangeDone(LoginRequiredMixin, TemplateView):
    """ アドレス変更メール送信完了 """
    template_name = 'register/email_change_done.html'

class EmailChangeComplete(LoginRequiredMixin, TemplateView):
    """ リンクを呼ばれた後に呼ばれる変更ビュー """
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内
    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest

        # token間違い
        except BadSignature:
            return HttpResponseBadRequest
        
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'
        

register/templates/register/axes_locked.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
    <title>店主.jp</title>
</head>
<body>
    <header>
    {% if messages %}
    {# Django のメッセージに記録している内容があればここで表示 #}
    <div class="container">
           {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
    </div>
    {% endif %}
    <h1>店主.jp</h1>
    </header>
        <div class="menu">
            <p class="first-p">連続で5回間違えたのでロックしました</p>
            <p class="last-p">また後ほどご利用ください</p>
        </div>
    <footer>
  	<p>© All rights reserved by 店主.jp</p>
  </footer>
</body>
</html>

register/templates/register/base.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
    <title>店主.jp</title>
</head>
<body>
    <header>
    {% if messages %}
    {# Django のメッセージに記録している内容があればここで表示 #}
    <div class="container">
           {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
    </div>
    {% endif %}
    <h1>店主.jp</h1>
    </header>
        <div class="menu">
        {% block content %}
        {% endblock  %}
        </div>
    <footer>
  	<p>© All rights reserved by 店主.jp</p>
  </footer>
</body>
</html>

register/templates/register/email_change_complete.html
{% extends "register/base.html" %}
{% block content %}
<p class="first-p">
    メールアドレスを変更しました。<br>
</p>
<p class="last-p"><a href="{% url 'register:login' %}">ログイン</a></p>

{% endblock %}

register/templates/register/email_change_done.html
{% extends "register/base.html" %}
{% block content %}
<p class="no-margin">
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
{% endblock %}

register/templates/register/email_change_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div>
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
<p class="last-p"><a href="{% url 'register:usertop' user.id %}">ユーザートップページへ戻る</a></p>
{% endblock %}

register/templates/register/logout.html
{% extends 'register/base.html' %}
{% block  %}
<p>ログアウトしました</p>
{% endblock  %}

register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
<p class="last-p"><a href="{% url 'register:usertop' user.id %}">ユーザートップページへ戻る</a></p>
{% endblock %}

register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
<p class="last-p"></p>

{% endblock %}

register/templates/register/password_reset_done.html
{% extends "register/base.html" %}
{% block content %}
<p class="no-margin">
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

register/templates/register/password_reset_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div>
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>

<p class="last-p"><a href="{% url 'register:login' %}">ログイン画面に戻る</a></p>

{% endblock %}

register/templates/register/user_create.html
{% extends "register/base.html" %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" >送信</button>
</form>
<p class="go-back"><a href="{% url 'register:login' %}" >ログイン画面へ戻る</a></p>
{% endblock %}

register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="user-create-done">
    <p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a href="{% url 'register:login' %}">ログイン</a>
</p>
</div>

{% endblock %}

register/templates/register/usertop.html
{% extends 'register/base.html' %}
{% block content %}
{% if request.user.pk == object.pk %}

    <div class="hello">
        <p>ようこそ{{ user }}</p>
    </div>
        {% for shop in user.shop.all %}
        {{ shop.name }}
        {% endfor %}
    {% comment %} <p><a href="{% url 'page:shoptop' shop.slug %}">{{ shop.name }}ショップページへ</a></p> {% endcomment %}

    {% comment %} <p><a href="{% url 'page:shoptop' object.shop.slug %}">ショップページへ</a></p> {% endcomment %}
    <p><a href="{% url 'register:email_change' %}">メールアドレスの変更</a></p>
    <p><a href="{% url 'register:password_change' %}">パスワード変更</a></p>
    <p></p>

    <p><a href="{% url 'page:shoplist' user.id %}">お店サイト管理ページへ</a></p>


    <p><a href="{% url 'page:shopcreate' user.id %}">新規お店サイト作成ページへ</a></p>
    <p class="last-p"><a href="{% url 'register:logout' %}">ログアウト</a></p>

{% else %}
<p class="first-p">異常が発生しました</p>
<p>お手数ですが再度ログインをお願い致します</p>
<p class="last-p"><a href="{% url 'register:login' %}">ログイン</a></p>

{% endif %}
{% endblock  %}